### PR TITLE
Fix crash in attempting to canonicalize paths longer than _MAX_PATH

### LINKED ISSUE #972: Ninja crashes due to Intel Compiler warnings
When trying to compile a C++ program using the Intel Compiler under Windows ninja will crash if the compiler outputs warnings like the following:

    warning #31001: The dll for reading and writing the pdb (for example, mspdb110.dll) could  not be found on your path. This is usually a configuration error. Compilation will continue using /Z7 instead of /Zi, but expect a similar error when you link your program.

When I disable this warning on the compiler command line the compile runs through without problems. I had a similar problem with the optimization diagnostic messages from the Intel Compiler which I also need to turn off.

I'm currently using a recent ninja version from git (Reported Version number 1.5.3)

If you need the ninja.build files to debug this problem, please let me know.

### PR DESCRIPTION
**Pull request by sgraham**
To fix #972.

### CODE REVIEW

File: src/includes_normalize-win32.cc [hunk 1]
```diff
@@ -96,8 +96,12 @@ string IncludesNormalize::Relativize(StringPiece path, const string& start) {
 
 string IncludesNormalize::Normalize(const string& input,
                                     const char* relative_to) {
-  char copy[_MAX_PATH];
+  char copy[_MAX_PATH + 1];
   size_t len = input.size();
+  if (len > _MAX_PATH) {
+    Warning("path too long '%s'\n", input.c_str());
+    return input;
```
Comment (martine) [inline src/includes_normalize-win32.cc]: Should we abort here?

File: src/includes_normalize-win32.cc [hunk 2]
```diff
@@ -96,8 +96,12 @@ string IncludesNormalize::Relativize(StringPiece path, const string& start) {
 
 string IncludesNormalize::Normalize(const string& input,
                                     const char* relative_to) {
-  char copy[_MAX_PATH];
+  char copy[_MAX_PATH + 1];
   size_t len = input.size();
+  if (len > _MAX_PATH) {
```
Comment (martine) [inline src/includes_normalize-win32.cc]: >= maybe?

File: src/includes_normalize-win32.cc [hunk 3]
```diff
@@ -96,8 +96,12 @@ string IncludesNormalize::Relativize(StringPiece path, const string& start) {
 
 string IncludesNormalize::Normalize(const string& input,
                                     const char* relative_to) {
-  char copy[_MAX_PATH];
+  char copy[_MAX_PATH + 1];
```
Comment (martine) [inline src/includes_normalize-win32.cc]: There's other use of MAX_PATH in this file.  Maybe it'd be good to wrap GetFullPathName as a helper function so that none of the other code is manually managing buffers?

File: src/includes_normalize-win32.cc (hunk 2 above)
Comment (sgraham) [inline src/includes_normalize-win32.cc]: Do you mean using >= in the comparison? I think it's correct as is, I made the buffer _MAX_PATH + 1 so that it can handle _MAX_PATH-lengthed paths which is as large as real paths should be.

Comment (martine) [inline src/includes_normalize-win32.cc]: Whoops, you are right.  I was thinking >= len or something.  Two problems in computer science I guess.

File: src/includes_normalize-win32.cc (hunk 1 above)
Comment (sgraham) [inline src/includes_normalize-win32.cc]: That seems fine also, up to you/Nico. One drawback is that I don't think we can do "death tests" with the non-gtest-test.h, but I could promote to an error return and print the message in the parent if that's preferable.

Comment (martine) [inline src/includes_normalize-win32.cc]: I think the rule is: if we will do the wrong thing from this point on it's good to quit loudly.  But if this instead has a mild consequence, like that we will always rebuild the file or something, then it's probably fine to warn.

Comment (sgraham) [inline src/includes_normalize-win32.cc]: I think there's potentially bad side-effects. It also indicates something pretty screwed up with the build, so I switched it to be fatal.

File: src/msvc_helper-win32.cc [hunk 4]
```diff
@@ -95,9 +95,15 @@ string CLParser::Parse(const string& output, const string& deps_prefix) {
...
     if (!include.empty()) {
-      include = IncludesNormalize::Normalize(include, NULL);
-      if (!IsSystemInclude(include))
-        includes_.insert(include);
+      string normalized;
+      string err;
+      if (!IncludesNormalize::Normalize(include, NULL, &normalized, &err)) {
+        Error("failed to normalize path: %s: %s\n", include.c_str(),
+              err.c_str());
+        exit(1);
```
Comment (nico) [inline src/msvc_helper-win32.cc]: Does Fatal() not work in this file?

Comment (sgraham) [inline src/msvc_helper-win32.cc]: Done.

**Comment by nico** [comment]
Thanks, looks fine. I personally prefer if random code wouldn't call exit (or Fatal) and I'd thread the error return through two more layers (to MSVCHelperMain / Builder::ExtractDeps) where there's existing exit hatches, but since this'll likely ~never happen in practice I suppose this is ok too.

**Comment by nico** [comment]
Thanks!

**Comment by nico** [comment]
Wait, did I just close this and not merge?

**Comment by nico** [comment]
…yeah, looks like it :-(

**Comment by sgraham** [comment]
Doh! I didn't notice in the barrage of spam that github sends.
